### ISSUE TITLE
Bug: Ctrl+C crashes shell

### ISSUE THREAD

**Issue by ofir-reich** [idlespork/idlespork#14]
When I press Ctrl+C to interrupt code while it's running, my shell sometimes crashes (and restarts). I get this error right before it happens:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Anaconda2\lib\site-packages\idlesporklib\run.py", line 329, in main
    MainThreadCaller.wait_for_call(1)
  File "C:\Program Files\Anaconda2\lib\site-packages\idlesporklib\run.py", line 198, in wait_for_call
    if not self.callEvent.wait(timeout):
  File "C:\Program Files\Anaconda2\lib\threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "C:\Program Files\Anaconda2\lib\threading.py", line 359, in wait
    _sleep(delay)
TypeError: 'int' object is not callable
```

**Comment by drorspei** [comment]
This is a cpython issue :(
https://bugs.python.org/issue23395
