### ISSUE TITLE
Options->Configure IDLE... "OK" button does not work

### ISSUE THREAD

**Issue by ofir-reich** [idlespork/idlespork#2]
On Ubuntu 14.04 at least. I press OK, nothing happens. The new key configurations (for example) are not saved.

**Comment by ofir-reich** [comment]
This doesn't happen immediately, only after changing the keys a few times.
When this happens, idlespork stops running commands and a new session of idlespork will also not start, giving the exception:
`Traceback (most recent call last):
  File "/usr/local/bin/idlespork", line 3, in <module>
    idlesporklib.PyShell.main()
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/PyShell.py", line 1669, in main
    shell = flist.open_shell()
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/PyShell.py", line 317, in open_shell
    self.pyshell = PyShell(self)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/PyShell.py", line 934, in __init__
    OutputWindow.__init__(self, flist, None, None)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/OutputWindow.py", line 15, in __init__
    EditorWindow.__init__(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/EditorWindow.py", line 239, in __init__
    text.bind("<<comment-region>>",self.comment_region_event)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/MultiCall.py", line 335, in bind
    self.__binders[triplet[1]].bind(triplet, func)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/MultiCall.py", line 214, in bind
    seq, handler)))
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1041, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 996, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: bad event type or keysym "Slash"`

This seems to be because I manually changed key settings to <Control-Key-Slash> [upper-case] instead of <Control-Key-slash> [lower case].
My only fix was to change the config-keys.cfg file in a text editor.

**Comment by liorgold** [comment]
I cannot reproduce the bug. Do you know what steps lead to the bug?

**Comment by ofir-reich** [comment]
It is this known issue in IDLE, it seems:
http://bugs.python.org/issue11437

So I think maybe we should close it.

Also, it seems like idlex might have a solution. Not sure. See description if idlex.py in:
http://idlex.sourceforge.net/extensions.html
