### ISSUE TITLE
RuntimeError('main thread is not in main loop')

### ISSUE THREAD

**Issue by ofir-reich** [idlespork/idlespork#8]
![selection_144](https://user-images.githubusercontent.com/8654211/26987791-b72b5fe0-4d01-11e7-8026-d9617e8ef2d7.png)

This happened with no warning, and then the window stopped responding completely. Python crashed, but is this related to idlespork?
It might be a Tkinter thing. See https://stackoverflow.com/questions/14694408/runtimeerror-main-thread-is-not-in-main-loop

I got this error dumped in shell:
[Errno 2] No such file or directory: '/home/ofir/.idlesporkhistory.pickle'
Tcl_AsyncDelete: async handler deleted by the wrong thread

**Comment by drorspei** [comment]
hey hey

it has happened to me too, in old pip version before new one. 
it's about the gui: somehow a gui call was made from a different thread. and it's always in the del method of PhotoImage. 
that's where my knowledge ends :(

I haven't worked enough with idle (not idlespork) to know if sometime's it also has this problem. 

let's start with system details. 
our office works with stock Ubuntu 15.04 and python 2.7.10.
what about you? 

I'll also search in bugs of idle and tkinter about this.

**Comment by ofir-reich** [comment]
Hey!

I'm using python 2.7.6 on Ubuntu 14.04.

**Comment by drorspei** [comment]
oh wow. I've never seen the shell messages you got. that's really disturbing. 
have to somehow find what's going on. 
I'm going to put traces on everything locally for a while and see if I get anywhere.

**Comment by ofir-reich** [comment]
Happened again. Got this dump in the Shell:

```
can't invoke "event" command: application has been destroyed
    while executing
"event generate $w <<ThemeChanged>>"
    (procedure "ttk::ThemeChanged" line 6)
    invoked from within
"ttk::ThemeChanged"
Tcl_AsyncDelete: async handler deleted by the wrong thread
```
And then after a while (with the python crashing):
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(*args)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/MultiCall.py", line 166, in handler
    r = l[i](event)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/AutoComplete.py", line 105, in autocomplete_event
    opened = self.open_completions(False, True, True)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/AutoComplete.py", line 168, in open_completions
    comp_lists = self.fetch_completions(comp_what, mode)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/AutoComplete.py", line 194, in fetch_completions
    (what, mode), {})
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/rpc.py", line 211, in remotecall
    return self.asyncreturn(seq)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/rpc.py", line 240, in asyncreturn
    response = self.getresponse(seq, wait=0.05)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/rpc.py", line 280, in getresponse
    response = self._getresponse(myseq, wait)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/rpc.py", line 300, in _getresponse
    response = self.pollresponse(myseq, wait)
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/rpc.py", line 425, in pollresponse
    self.handle_EOF()
  File "/usr/local/lib/python2.7/dist-packages/idlesporklib/PyShell.py", line 377, in handle_EOF
    raise EOFError
EOFError

```

**Comment by drorspei** [comment]
I must fix this issue. 
this trace is the most informative I've seen with this bug, it really helps. 
it implicates autocomplete and says where to look. I actually have a good guess on what to do now.

**Comment by drorspei** [comment]
Hey hey, quick update:
I'm still looking to solve this, still not sure why it happens.
I figured out today how to see lots of debug messages by setting `debugging=True` in `rpc.py` (remember that I'm still new to all of this code).
While trying to reproduce the "horrible bug", I was typing many things and clicking enter (I also automated this process), and then at some point idlespork froze - but didn't crash.

Then I solved a bug!
It seems that there has always been a design bug in how messages from kernel to gui were processed. Basically, if you run a lot of stuff fast, and each thing sent responses between pythons, then one message processing could accidentally poll a message response that was meant for another call, and then that message would be discarded.
Another polling loop waiting for its message to come would hang.

I'm not sure this is related to the horrible bug, but I definitely learnt most of the way idlespork works now. So I hope to have a good lead soon.

**Comment by drorspei** [comment]
Hey,
So the bug above was not the horrible bug. But I have made some serious progress today.
After a suggestion from Geva today, I mokey-patched the delete method of PhotoImage to print went it happens. Then I found out it happens every time I use matplotlib. Then, for the first time, I found a way to reproduce the horrible bug:

```
import threading
from matplotlib import pyplot as plt
import time

def shimi():
    time.sleep(0.1)
    z = plt.plot([1.])
    plt.close()

threading.Thread(target=shimi).start()
```

That's it: calling `plt.close()` from a non-main thread crashes python - even when not in idlespork. So why does the horrible bug happen in idlespork and not in, say, ipython? I don't know yet.
But what I do know is how to start solving this.

I've written a patch that retains a copy of a PhotoImage instance that was going to be deleted in the wrong thread (available in my fork). The above doesn't crash my shell now, but if I run it enough times my idlespork gets stuck. Still working on it, hopefully I'll have a complete solution soon.

**Comment by drorspei** [comment]
I think I fixed this bug. I've been running with some patch code for a month and my shell hasn't crashed from this bug once. I have seen the crash messages, which would be hard to suppress, but no crash occurs anymore. I'll submit a pull request soon.
